twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        webSiteProtocol: '%webSiteProtocol%'
        webSiteName: '%webSiteName%'
        webSiteDomainName: '%webSiteDomainName%'
        webSiteHomeUrl: '%webSiteHomeUrl%'
        webSiteEmailAddress: '%webSiteEmailAddress%'

when@test:
    twig:
        strict_variables: true
